/*
 * Kaisatsu (改札) — verify tickets issued by Kippu.
 *
 * Generated by `cargo xtask header`; do not edit.
 *
 *     KaisatsuKey keys[] = {{ .public_key = { ... } }};
 *     KaisatsuTicket ticket;
 *     KaisatsuStatus status = kaisatsu_verify(keys, 1, bytes, len, &ticket);
 *     if (status != KAISATSU_STATUS_OK) puts(kaisatsu_status_message(status));
 */

#ifndef KAISATSU_H
#define KAISATSU_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The largest ticket Kaisatsu accepts, in bytes. Size ticket buffers with it.
#define KAISATSU_MAX_TICKET_LEN 2048

// Result of a Kaisatsu call. `KAISATSU_STATUS_OK` is zero; everything else is a rejection.
enum KaisatsuStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  // Success.
  KAISATSU_STATUS_OK = 0,
  // The bytes are not a well-formed ticket (or not valid Base45).
  KAISATSU_STATUS_MALFORMED = 1,
  // Unknown protocol version.
  KAISATSU_STATUS_UNSUPPORTED_VERSION = 2,
  // Unknown signature algorithm.
  KAISATSU_STATUS_UNSUPPORTED_ALGORITHM = 3,
  // Signed by a key that is not trusted.
  KAISATSU_STATUS_UNKNOWN_KEY = 4,
  // The ticket was forged or altered.
  KAISATSU_STATUS_BAD_SIGNATURE = 5,
  // The validity window has not started.
  KAISATSU_STATUS_NOT_YET_VALID = 6,
  // The validity window has ended.
  KAISATSU_STATUS_EXPIRED = 7,
  // A public key is not a usable Ed25519 key.
  KAISATSU_STATUS_INVALID_KEY = 8,
  // A required pointer argument was null.
  KAISATSU_STATUS_NULL_POINTER = 9,
  // An output buffer is too small.
  KAISATSU_STATUS_BUFFER_TOO_SMALL = 10,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum KaisatsuStatus KaisatsuStatus;
#else
typedef int32_t KaisatsuStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// A trusted Ed25519 public key.
typedef struct {
  // The 32-byte public key, as published at `/.well-known/kippu/ticket-keys`.
  uint8_t public_key[32];
} KaisatsuKey;

// The claims of a verified ticket.
//
// `issuer` and `extensions` point into the ticket buffer passed to `kaisatsu_verify` and are
// valid only as long as that buffer is.
typedef struct {
  // Protocol version.
  uint8_t version;
  // Id of the key that signed the ticket.
  uint8_t key_id[8];
  // Event the ticket admits to (UUID bytes).
  uint8_t event_id[16];
  // Unique ticket id (UUID bytes). Use it to detect re-use.
  uint8_t ticket_id[16];
  // Ticket type (UUID bytes).
  uint8_t ticket_type_id[16];
  // Start of validity, inclusive, in Unix seconds.
  uint64_t valid_from;
  // End of validity, exclusive, in Unix seconds.
  uint64_t valid_until;
  // Issue time in Unix seconds.
  uint64_t issued_at;
  // UTF-8 issuer, *not* NUL-terminated.
  const uint8_t *issuer;
  // Length of `issuer` in bytes.
  size_t issuer_len;
  // Extensions in wire encoding; read them with `kaisatsu_ticket_extension`.
  const uint8_t *extensions;
  // Length of `extensions` in bytes.
  size_t extensions_len;
} KaisatsuTicket;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Verifies a binary ticket against a list of trusted keys.
//
// On success, writes the claims to `*out` and returns `KAISATSU_STATUS_OK`. Pointers inside
// `*out` borrow from `ticket`.
//
// # Safety
//
// - `keys` must point to `key_count` valid `KaisatsuKey`s (or may be null if `key_count` is 0).
// - `ticket` must point to `ticket_len` readable bytes.
// - `out` must point to writable memory for one `KaisatsuTicket`.
KaisatsuStatus kaisatsu_verify(const KaisatsuKey *keys,
                               size_t key_count,
                               const uint8_t *ticket,
                               size_t ticket_len,
                               KaisatsuTicket *out);

// Checks that `now` (Unix seconds) lies within the ticket's validity window.
//
// Returns `KAISATSU_STATUS_OK`, `KAISATSU_STATUS_NOT_YET_VALID` or `KAISATSU_STATUS_EXPIRED`.
//
// # Safety
//
// `ticket` must point to a `KaisatsuTicket` filled in by `kaisatsu_verify`.
KaisatsuStatus kaisatsu_ticket_check_time(const KaisatsuTicket *ticket, uint64_t now);

// Looks up the extension with the given tag. Returns `true` and sets `*value` / `*value_len`
// if the ticket carries it.
//
// # Safety
//
// - `ticket` must point to a `KaisatsuTicket` filled in by `kaisatsu_verify`, whose ticket
//   buffer is still alive.
// - `value` and `value_len` must be writable.
bool kaisatsu_ticket_extension(const KaisatsuTicket *ticket,
                               uint8_t tag,
                               const uint8_t **value,
                               size_t *value_len);

#if defined(KAISATSU_BASE45)
// Decodes Base45 text, one way to carry a ticket in a QR code, into `out`.
//
// `KAISATSU_MAX_TICKET_LEN` bytes of output always suffice. Only exported with the `base45`
// feature; define `KAISATSU_BASE45` to declare it.
//
// # Safety
//
// - `text` must point to `text_len` readable bytes.
// - `out` must point to `out_capacity` writable bytes.
// - `out_len` must be writable.
KaisatsuStatus kaisatsu_base45_decode(const char *text,
                                      size_t text_len,
                                      uint8_t *out,
                                      size_t out_capacity,
                                      size_t *out_len);
#endif

// Checks that a public key is a usable Ed25519 key, and writes its key id to `out_key_id`
// (if not null). Call it once at startup to catch misconfigured keys early: `kaisatsu_verify`
// silently ignores unusable keys.
//
// # Safety
//
// `key` must point to a `KaisatsuKey`; `out_key_id` must be null or point to 8 writable bytes.
KaisatsuStatus kaisatsu_key_check(const KaisatsuKey *key, uint8_t *out_key_id);

// A static, NUL-terminated description of a status, e.g. `"ピンポーン🔔 BadSignature"`.
// Never returns null.
const char *kaisatsu_status_message(int32_t status);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* KAISATSU_H */
