allow-unwrap-in-tests = true
allow-expect-in-tests = true
allow-panic-in-tests = true
allow-indexing-slicing-in-tests = true
doc-valid-idents = ["OpenAPI", "EdDSA", "SQLite", "PostgreSQL", "MySQL", "JetStream", "WebAssembly", "WeChat", "InnoDB", "MinIO", ".."]
